### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by advance24th** [The-Imortal-Crasher/jzxy.cf#2]
why the fuck would you make this? it made me lose 20 hours of fucking work when i opened it.
i swear im going to fucking kill you if you dont pay me for the work i lost

**Comment by The-Imortal-Crasher** [comment]
I have stated a lot in a lot of files and in the readme.md that I don't take responsibility for your actions, you stated that you opened the website. that is your fault.

and I will not pay you money for work you lost. maybe take precautions and save your work. also don't use the issues page to complain about the fact you lost your work to a browser crasher website.
