### ISSUE TITLE
issue with index.html

### ISSUE THREAD

**Issue by relaybots** [The-Imortal-Crasher/jzxy.cf#3]
While I was looking in your code I noticed that index.html uses old META properties from the 2000's that uses
excessive space in your index file, use the newer version <meta property=""> which allows very simple styling when 
website is linked from things like discord.

**Comment by The-Imortal-Crasher** [comment]
thanks for the information I'll look into that

**Comment by The-Imortal-Crasher** [comment]
thanks for the help!
